project_id = "rhjgzlaksbmzyidybgyf"

[functions.analyze-image]
verify_jwt = false

[functions.share-report]
verify_jwt = false

[functions.cleanup-stuck-exams]
verify_jwt = false

[functions.analyze-feedback]
verify_jwt = false
